import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from 'react-hot-toast';
import Navbar from "@/components/Navbar";
import { AuthModalProvider } from '@/components/auth/AuthModalContext';
import AuthModal from "@/components/auth/AuthModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ToLetRooms",
  description: "Generated by Saurabh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <AuthModalProvider>
        {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
        <Toaster position="top-right" />
        <Navbar/>
            {children}
          {/* </ThemeProvider> */}
          <AuthModal/>
          </AuthModalProvider>
          {/* {children} */}
      </body>
    </html>
  );
}
